// tests/unit/run-tests.test.ts
// Phase A Section 3: real test execution tests.
//
// Proves:
//   1. runTests() on server/ returns real pass/fail counts (648+ tests)
//   2. runTests() with coverage returns real coverage percentages
//   3. Server stays responsive during test run (concurrent /api/health
//      returns promptly — the concrete proof spawn() solved the blocking
//      concern)
//   4. Fixed allowlist rejects arbitrary commands
//   5. Missing package.json fails honestly

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { __test__ as runTestsTest } from '../../src/orchestration/run-tests.js';
import { QaTesterAgent } from '../../src/agents/qa-tester/index.js';
import { existsSync, mkdtempSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { spawn } from 'node:child_process';
import http from 'node:http';
import { fileURLToPath } from 'node:url';

describe('Phase A Section 3 — Real test execution', () => {
  const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

  // ════════════════════════════════════════════════════════════════════
  // TEST 1: runTests() on server/ — real pass/fail counts
  // ════════════════════════════════════════════════════════════════════
  it('runTests() on server/ returns real pass/fail counts matching the actual suite', async () => {
    const result = await runTestsTest.runTests(projectRoot, {
      targetDir: 'server',
      timeoutMs: 240_000, // 4min — the real suite takes ~94s, give headroom
    });

    // The suite has 648 tests (confirmed in Section 0 + this session's runs)
    expect(result.success).toBe(true);
    expect(result.totalTests).toBeGreaterThan(600); // 648 as of this commit
    expect(result.passed).toBe(result.totalTests);
    expect(result.failed).toBe(0);
    expect(result.durationMs).toBeGreaterThan(10_000); // real run takes ~94s
    expect(result.durationMs).toBeLessThan(240_000); // but not > 4min
  }, 300_000); // 5min test timeout

  // ════════════════════════════════════════════════════════════════════
  // TEST 2: runTests() with coverage — real coverage percentages
  // ════════════════════════════════════════════════════════════════════
  it('runTests() with coverage returns real coverage summary (not fabricated)', async () => {
    const result = await runTestsTest.runTests(projectRoot, {
      targetDir: 'server',
      coverage: true,
      timeoutMs: 240_000,
    });

    // Log the result for debugging if it failed
    if (!result.success) {
      console.log('Coverage test failed:', {
        reason: result.reason,
        totalTests: result.totalTests,
        passed: result.passed,
        failed: result.failed,
        rawOutputPreview: result.rawOutput.slice(0, 500),
      });
    }

    expect(result.success).toBe(true);
    expect(result.coverageSummary).toBeDefined();
    const cov = result.coverageSummary!;
    // Coverage percentages are real numbers between 0-100. The vitest config
    // sets thresholds at 10%, so we expect > 10% for all (the config would
    // fail the run otherwise). We don't assert exact values (they change as
    // code changes) — we assert they're sane + non-zero.
    expect(cov.statementsPct).toBeGreaterThan(10);
    expect(cov.branchesPct).toBeGreaterThan(10);
    expect(cov.functionsPct).toBeGreaterThan(10);
    expect(cov.linesPct).toBeGreaterThan(10);
    expect(cov.statementsPct).toBeLessThanOrEqual(100);
    // Verify the coverage-final.json file actually exists (proves it was
    // generated by the real test run, not fabricated)
    expect(existsSync(join(projectRoot, 'server', 'coverage', 'coverage-final.json'))).toBe(true);
  }, 300_000);

  // ════════════════════════════════════════════════════════════════════
  // TEST 3: Server stays responsive during test run (THE key proof)
  // ════════════════════════════════════════════════════════════════════
  it('concurrent HTTP request returns promptly while runTests() is mid-flight (spawn non-blocking)', async () => {
    // Start a tiny HTTP server that responds to /health instantly.
    // While runTests() is running, fire a request to this server + measure
    // how long it takes to respond. If spawn() is truly non-blocking, the
    // request should return in < 500ms even though the test suite takes
    // ~94s. If we'd used execSync, the request would hang for 94s.
    const server = http.createServer((req, res) => {
      if (req.url === '/health') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'ok', ts: Date.now() }));
      } else {
        res.writeHead(404);
        res.end();
      }
    });

    await new Promise<void>((resolve) => server.listen(0, resolve));
    const port = (server.address() as any).port;

    try {
      // Start runTests() — DON'T await it yet. It starts running in the
      // background (spawn is non-blocking).
      const testPromise = runTestsTest.runTests(projectRoot, {
        targetDir: 'server',
        timeoutMs: 240_000,
      });

      // Give the test process a moment to spin up + start consuming CPU.
      await new Promise((r) => setTimeout(r, 2000));

      // Fire the HTTP request WHILE tests are running. Measure response time.
      const reqStart = Date.now();
      const response = await new Promise<{ status: number; body: string; elapsed: number }>((resolve) => {
        const req = http.get(`http://localhost:${port}/health`, (res) => {
          let body = '';
          res.on('data', (chunk) => { body += chunk; });
          res.on('end', () => {
            resolve({ status: res.statusCode!, body, elapsed: Date.now() - reqStart });
          });
        });
        req.on('error', (err) => {
          resolve({ status: 0, body: err.message, elapsed: Date.now() - reqStart });
        });
      });

      // ── THE KEY ASSERTION ───────────────────────────────────────────
      // The HTTP request must return PROMPTLY (well under the 94s test
      // duration). If spawn() were blocking, this would take ~94s.
      // We allow up to 5s for overhead (process startup, event loop latency)
      // — anything under 5s proves non-blocking.
      expect(response.status).toBe(200);
      expect(response.elapsed).toBeLessThan(5000); // < 5s = non-blocking
      expect(response.body).toContain('"ok"');

      // Wait for the test run to finish (don't leave it dangling)
      const testResult = await testPromise;
      expect(testResult.success).toBe(true);
      expect(testResult.totalTests).toBeGreaterThan(600);
    } finally {
      server.close();
    }
  }, 300_000);

  // ════════════════════════════════════════════════════════════════════
  // TEST 4: Fixed allowlist — buildTestCommand only produces allowed commands
  // ════════════════════════════════════════════════════════════════════
  it('buildTestCommand: only produces npm test / npm run test:coverage', () => {
    // server/ without coverage — excludes the run-tests test file to prevent
    // infinite recursion when runTests() is invoked from within a test run
    expect(runTestsTest.buildTestCommand('server', false))
      .toBe('npm test -- --reporter=json --exclude tests/unit/run-tests.test.ts');
    // server/ with coverage
    expect(runTestsTest.buildTestCommand('server', true))
      .toBe('npm run test:coverage -- --reporter=json --exclude tests/unit/run-tests.test.ts');
    // app/ (coverage flag ignored — app has no coverage config)
    expect(runTestsTest.buildTestCommand('app', false)).toBe('npm test -- --reporter=json');
    expect(runTestsTest.buildTestCommand('app', true)).toBe('npm test -- --reporter=json');
  });

  // ════════════════════════════════════════════════════════════════════
  // TEST 5: Missing package.json fails honestly
  // ════════════════════════════════════════════════════════════════════
  it('runTests() on a directory without package.json fails honestly', async () => {
    const fakeRoot = mkdtempSync(join(tmpdir(), 'run-tests-missing-'));
    try {
      const result = await runTestsTest.runTests(fakeRoot, {
        targetDir: 'server',
        timeoutMs: 5000,
      });

      expect(result.success).toBe(false);
      expect(result.reason).toContain('no package.json');
      expect(result.totalTests).toBe(0);
    } finally {
      rmSync(fakeRoot, { recursive: true, force: true });
    }
  });

  // ════════════════════════════════════════════════════════════════════
  // TEST 6: QaTesterAgent.runTestsSuite() wires through to runTests()
  // ════════════════════════════════════════════════════════════════════
  it('QaTesterAgent.runTestsSuite() calls runTests() + returns real counts', async () => {
    const agent = new QaTesterAgent();
    const result = await agent.runTestsSuite(projectRoot, {
      targetDir: 'server',
      timeoutMs: 240_000,
    });

    expect(result.success).toBe(true);
    expect(result.totalTests).toBeGreaterThan(600);
    expect(result.passed).toBe(result.totalTests);
    expect(result.failed).toBe(0);
  }, 300_000);

  // ════════════════════════════════════════════════════════════════════
  // TEST 7: parseVitestJson handles real vitest JSON output
  // ════════════════════════════════════════════════════════════════════
  it('parseVitestJson: extracts counts from real vitest JSON shape', () => {
    const sampleJson = JSON.stringify({
      numTotalTests: 6,
      numPassedTests: 5,
      numFailedTests: 1,
      numPendingTests: 0,
      success: false,
      testResults: [],
    });

    const parsed = runTestsTest.parseVitestJson(sampleJson);
    expect(parsed).not.toBeNull();
    expect(parsed!.numTotalTests).toBe(6);
    expect(parsed!.numPassedTests).toBe(5);
    expect(parsed!.numFailedTests).toBe(1);
    expect(parsed!.success).toBe(false);
  });

  it('parseVitestJson: handles leading text before JSON', () => {
    const sampleWithBanner = `vitest v1.0.0\nrunning tests...\n${JSON.stringify({
      numTotalTests: 3, numPassedTests: 3, numFailedTests: 0, numPendingTests: 0, success: true,
    })}`;

    const parsed = runTestsTest.parseVitestJson(sampleWithBanner);
    expect(parsed).not.toBeNull();
    expect(parsed!.numTotalTests).toBe(3);
    expect(parsed!.success).toBe(true);
  });

  it('parseVitestJson: returns null for non-JSON', () => {
    expect(runTestsTest.parseVitestJson('not json at all')).toBeNull();
    expect(runTestsTest.parseVitestJson('')).toBeNull();
  });
});
