// scripts/full-voice-pipeline-test.mts
//
// Phase E Final Proof — Full Live Voice Pipeline Test.
//
// Starts the real server, authenticates, starts a voice session, sends real
// audio (generated by ZaiTTSProvider saying "What time is it?"), triggers
// turn-end, and captures the full chain of voice:* + agent:* events.
// Measures end-to-end round-trip latency from audio-in to audio-out.
//
// Run: node --env-file=server/.env --import tsx scripts/full-voice-pipeline-test.mts [provider]
//   provider: 'zai' (default) or 'kokoro'

import { WebSocket } from 'ws';
import { readFileSync, existsSync } from 'node:fs';
import { spawn, type ChildProcess } from 'node:child_process';
import { randomUUID } from 'node:crypto';

const SERVER_URL = 'http://localhost:3001';
const WS_URL = 'ws://localhost:3001/ws';
const AUDIO_PATH = '/tmp/voice-test-input.wav';
const PROVIDER = process.argv[2] ?? 'zai';

interface CapturedEvent {
  event: string;
  payload: any;
  ts: number;
  receivedAt: number;
}

async function sleep(ms: number) {
  return new Promise(r => setTimeout(r, ms));
}

async function waitForServer(timeoutMs = 30000): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(`${SERVER_URL}/api/health`);
      if (res.ok) {
        console.log(`Server reachable after ${Date.now() - start}ms`);
        return;
      }
    } catch {
      // not up yet
    }
    await sleep(500);
  }
  throw new Error(`Server not reachable after ${timeoutMs}ms`);
}

async function registerAndLogin(): Promise<{ token: string; userId: string }> {
  // Register a test user
  const email = `voice-test-${Date.now()}@example.com`;
  const password = 'test-password-123';
  console.log(`Registering test user: ${email}`);
  try {
    await fetch(`${SERVER_URL}/api/auth/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password, name: 'Voice Test' }),
    });
  } catch {
    // may already exist — try login next
  }

  // Login
  const loginRes = await fetch(`${SERVER_URL}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });
  if (!loginRes.ok) {
    throw new Error(`Login failed: ${loginRes.status} ${await loginRes.text()}`);
  }
  const loginBody = await loginRes.json() as any;
  console.log(`Logged in. Token: ${loginBody.token?.slice(0, 20)}...`);
  return { token: loginBody.token, userId: loginBody.user?.id ?? 'unknown' };
}

async function setProvider(token: string, provider: string): Promise<void> {
  console.log(`Setting voice provider to '${provider}'...`);
  const res = await fetch(`${SERVER_URL}/api/voice/settings`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify({ provider }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Failed to set provider: ${res.status} ${body}`);
  }
  const data = await res.json() as any;
  console.log(`Provider set: ${data.settings.provider}`);
}

async function startVoiceSession(token: string): Promise<string> {
  console.log('Starting voice session...');
  const res = await fetch(`${SERVER_URL}/api/voice/live/start`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify({}),
  });
  if (!res.ok) {
    throw new Error(`Failed to start voice session: ${res.status} ${await res.text()}`);
  }
  const data = await res.json() as any;
  console.log(`Session started: ${data.sessionId}`);
  return data.sessionId;
}

async function endVoiceSession(token: string, sessionId: string): Promise<void> {
  try {
    await fetch(`${SERVER_URL}/api/voice/live/${sessionId}/end`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${token}` },
    });
    console.log(`Session ended: ${sessionId}`);
  } catch (err: any) {
    console.warn(`End session failed (non-critical): ${err.message}`);
  }
}

async function runPipelineTest(token: string, sessionId: string): Promise<{
  events: CapturedEvent[];
  audioInTime: number;
  audioOutTime: number | null;
  roundTripMs: number | null;
  transcript: string | null;
  agentResponse: string | null;
  audioBase64: string | null;
}> {
  return new Promise((resolve, reject) => {
    const events: CapturedEvent[] = [];
    const audioBytes = readFileSync(AUDIO_PATH);
    const audioInTime = Date.now();

    const ws = new WebSocket(`${WS_URL}?token=${token}&projectId=00000000-0000-0000-0000-000000000000`);

    let audioOutTime: number | null = null;
    let transcript: string | null = null;
    let agentResponse: string | null = null;
    let audioBase64: string | null = null;

    const timeout = setTimeout(() => {
      ws.close();
      resolve({
        events,
        audioInTime,
        audioOutTime,
        roundTripMs: audioOutTime ? audioOutTime - audioInTime : null,
        transcript,
        agentResponse,
        audioBase64,
      });
    }, 120000);  // 2 min timeout

    ws.on('open', () => {
      console.log('WS connected. Sending audio...');

      // Option C fix: send pure audio data — no sessionId header.
      // The server routes the audio to the user's active voice session
      // via their WS auth state (state.claims.sub).
      ws.send(audioBytes);

      console.log(`Sent ${audioBytes.length} bytes of audio. Sending turn-end...`);

      // Small delay to ensure audio is received before turn-end
      setTimeout(() => {
        ws.send(JSON.stringify({
          event: 'voice:turn-end',
          payload: { sessionId },
          ts: Date.now(),
          id: randomUUID(),
        }));
        console.log('Turn-end sent. Waiting for response...');
      }, 500);
    });

    ws.on('message', (data: Buffer, isBinary: boolean) => {
      if (isBinary) return;  // ignore binary frames from server
      try {
        const msg = JSON.parse(data.toString());
        const event: CapturedEvent = {
          event: msg.event,
          payload: msg.payload,
          ts: msg.ts ?? 0,
          receivedAt: Date.now(),
        };
        events.push(event);

        // Log each event as it arrives
        const elapsed = event.receivedAt - audioInTime;
        const preview = JSON.stringify(msg.payload).slice(0, 120);
        console.log(`  [+${elapsed}ms] ${msg.event}: ${preview}`);

        // Track key events
        if (msg.event === 'voice:transcript') {
          transcript = msg.payload?.text ?? null;
        }
        if (msg.event === 'voice:agent-response') {
          agentResponse = msg.payload?.text ?? null;
          audioBase64 = msg.payload?.audioBase64 ?? null;
          audioOutTime = Date.now();
          // We got the final response — resolve after a short delay to catch any trailing events
          setTimeout(() => {
            clearTimeout(timeout);
            ws.close();
            resolve({
              events,
              audioInTime,
              audioOutTime,
              roundTripMs: audioOutTime! - audioInTime,
              transcript,
              agentResponse,
              audioBase64,
            });
          }, 1000);
        }
        if (msg.event === 'voice:error') {
          console.error(`Voice error: ${JSON.stringify(msg.payload)}`);
          // Don't reject — capture the error and resolve with what we have
        }
      } catch (err) {
        console.warn('Failed to parse WS message:', err);
      }
    });

    ws.on('error', (err: Error) => {
      clearTimeout(timeout);
      console.error('WS error:', err.message);
      reject(err);
    });

    ws.on('close', () => {
      clearTimeout(timeout);
      // Resolve with what we have if not already resolved
      resolve({
        events,
        audioInTime,
        audioOutTime,
        roundTripMs: audioOutTime ? audioOutTime - audioInTime : null,
        transcript,
        agentResponse,
        audioBase64,
      });
    });
  });
}

async function main() {
  console.log('='.repeat(70));
  console.log(`PHASE E FINAL PROOF — Full Live Voice Pipeline Test`);
  console.log(`Provider: ${PROVIDER}`);
  console.log('='.repeat(70));

  // ── 0. Verify test audio exists ───────────────────────────────────────
  if (!existsSync(AUDIO_PATH)) {
    console.error(`Test audio not found at ${AUDIO_PATH}. Run generate-voice-test-audio.mts first.`);
    process.exit(1);
  }
  const audioStat = readFileSync(AUDIO_PATH);
  console.log(`Test audio: ${AUDIO_PATH} (${audioStat.length} bytes)`);

  // ── 1. Start the server ──────────────────────────────────────────────
  console.log('\n1. Starting server...');
  const serverProc = spawn('npx', ['tsx', 'src/index.ts'], {
    cwd: '/home/z/my-project/extracted/code_siren/server',
    stdio: 'pipe',
    env: { ...process.env },
  });

  let serverOutput = '';
  serverProc.stdout?.on('data', (data: Buffer) => {
    const text = data.toString();
    serverOutput += text;
    // Log key server messages (filter noise)
    for (const line of text.split('\n')) {
      if (line.includes('voice') || line.includes('TTS') || line.includes('tts') || line.includes('HTTP') || line.includes('WS') || line.includes('error') || line.includes('Error') || line.includes('agent') || line.includes('sidecar')) {
        console.log(`  [server] ${line}`);
      }
    }
  });
  serverProc.stderr?.on('data', (data: Buffer) => {
    const text = data.toString();
    serverOutput += text;
    for (const line of text.split('\n')) {
      if (line.trim()) console.log(`  [server:err] ${line}`);
    }
  });

  try {
    await waitForServer(30000);

    // ── 2. Auth ──────────────────────────────────────────────────────
    console.log('\n2. Authenticating...');
    const { token, userId } = await registerAndLogin();

    // ── 3. Set provider ──────────────────────────────────────────────
    console.log(`\n3. Setting provider to '${PROVIDER}'...`);
    await setProvider(token, PROVIDER);

    // ── 4. Start voice session ───────────────────────────────────────
    console.log('\n4. Starting voice session...');
    const sessionId = await startVoiceSession(token);

    // ── 5. Run the pipeline test ─────────────────────────────────────
    console.log('\n5. Running pipeline test (sending audio + capturing events)...');
    const result = await runPipelineTest(token, sessionId);

    // ── 6. End session ───────────────────────────────────────────────
    console.log('\n6. Ending voice session...');
    await endVoiceSession(token, sessionId);

    // ── 7. Report results ────────────────────────────────────────────
    console.log('\n' + '='.repeat(70));
    console.log('PIPELINE TEST RESULTS');
    console.log('='.repeat(70));

    console.log('\nEvents captured (in order):');
    for (const e of result.events) {
      console.log(`  +${e.receivedAt - result.audioInTime}ms  ${e.event}`);
    }

    console.log('\nKey metrics:');
    console.log(`  Audio sent at:        ${result.audioInTime}`);
    console.log(`  Audio received at:    ${result.audioOutTime ?? '(not received)'}`);
    console.log(`  Round-trip latency:   ${result.roundTripMs !== null ? result.roundTripMs + 'ms' : 'N/A (no audio out)'}`);
    console.log(`  ASR transcript:       "${result.transcript ?? '(none)'}"`);
    console.log(`  Agent response:       "${(result.agentResponse ?? '(none)').slice(0, 100)}${(result.agentResponse ?? '').length > 100 ? '...' : ''}"`);
    console.log(`  TTS audio:            ${result.audioBase64 ? result.audioBase64.length + ' chars base64' : '(none)'}`);

    // Verify the chain
    console.log('\nChain verification:');
    const eventNames = result.events.map(e => e.event);
    const hasTranscript = eventNames.includes('voice:transcript');
    const hasAgentStart = eventNames.includes('voice:agent-start');
    const hasAgentChunk = eventNames.includes('voice:agent-chunk');
    const hasAgentResponse = eventNames.includes('voice:agent-response');
    const hasAgentComplete = eventNames.includes('agent:complete');

    console.log(`  ASR → voice:transcript:     ${hasTranscript ? '✓' : '✗ FAIL'}`);
    console.log(`  Agent → voice:agent-start:  ${hasAgentStart ? '✓' : '✗ FAIL'}`);
    console.log(`  Agent → voice:agent-chunk:  ${hasAgentChunk ? '✓' : '✗ (may not fire for short responses)'}`);
    console.log(`  Agent → agent:complete:     ${hasAgentComplete ? '✓' : '✗ (standard event from executeAndWait)'}`);
    console.log(`  TTS → voice:agent-response: ${hasAgentResponse ? '✓' : '✗ FAIL'}`);

    if (result.audioBase64) {
      // Verify WAV header
      const wavBytes = Buffer.from(result.audioBase64, 'base64');
      const riff = wavBytes.slice(0, 4).toString('ascii');
      const wave = wavBytes.slice(8, 12).toString('ascii');
      console.log(`  TTS audio WAV header:       ${riff === 'RIFF' && wave === 'WAVE' ? '✓ valid' : '✗ invalid'} (${riff}/${wave})`);
    }

    // Overall verdict
    const success = hasTranscript && hasAgentStart && hasAgentResponse && result.audioBase64 !== null;
    console.log(`\nOverall: ${success ? '✓ PIPELINE PASSED' : '✗ PIPELINE FAILED — see chain above'}`);

    // Save results for the report
    console.log(`\n--- Server log excerpt (voice-related) ---`);
    const voiceLogs = serverOutput.split('\n').filter(line =>
      line.includes('voice') || line.includes('tts') || line.includes('TTS') || line.includes('sidecar') || line.includes('agent') || line.includes('ASR') || line.includes('asr')
    );
    for (const line of voiceLogs.slice(-30)) {
      console.log(`  ${line}`);
    }

    if (!success) {
      process.exit(1);
    }

  } finally {
    // Kill the server
    console.log('\nStopping server...');
    serverProc.kill('SIGTERM');
    await sleep(2000);
    if (!serverProc.killed) {
      serverProc.kill('SIGKILL');
    }
  }
}

main().catch(err => {
  console.error('FATAL:', err);
  process.exit(1);
});
